### ISSUE TITLE
Failure when using the `--watch-files` feature

### ISSUE THREAD

**Issue by magthe** [tninja/aider.el#25]
Aider has gained the ability to watch for commands in comments and act on them (documented [here](https://aider.chat/docs/usage/watch.html#ai-comments)). Unfortunately enabling that in `aider.el` isn't working, it causes the following exception

```
> Exception in thread Thread-2 (watch_files):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/elrond/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 151, in watch_files
    raise e
  File "/home/elrond/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 146, in watch_files
    self.io.interrupt_input()
  File "/home/elrond/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/io.py", line 393, in interrupt_input
    self.prompt_session.app.exit()
  File "/home/elrond/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 1289, in exit
    raise Exception("Application is not running. Application.exit() failed.")
Exception: Application is not running. Application.exit() failed.
```

It would be absolutely wonderful to have this feature work with `aider.el`.

**Comment by magthe** [comment]
I thought maybe that `--no-fancy-input` would be a workaround, but it wasn't because surprisingly `--watch-files` and `--no-fancy-input` don't work together: https://github.com/Aider-AI/aider/issues/2600

**Comment by tninja** [comment]
Confirmed the exception.. it might because comint buffer is not a full functional term.
I am wondering is there a corresponding command in aider, to manually trigger the scan and the follow up action? if there is, we can easily add a menu item for it. It won't take much more effort than automatically triggered

**Comment by tninja** [comment]
Seems that adding the following code to commands.py in aider, can add a new command /process_comment_ai, it will manually scan added files and do the magic. tested in aider code base.
`
    def cmd_process_comment_ai(self, args=""):
        "Process any AI comments in tracked files"
        from aider.watch import FileWatcher

        class SafeFileWatcher(FileWatcher):
            def start(self):
                # Override to do nothing
                pass

            def stop(self):
                # Override to do nothing
                pass

        # Create a temporary watcher that won't do file monitoring
        watcher = SafeFileWatcher(self.coder)

        # Get all files in chat
        for fname in self.coder.abs_fnames:
            watcher.changed_files.add(fname)

        # Process the changes without any file monitoring
        return watcher.process_changes()
`

But this will need to change the aider code base. not sure if it is OK

**Comment by magthe** [comment]
That sounds like a nice way of dealing with it. Will you put together a PR for `aider` itself?

**Comment by tninja** [comment]
Opened this PR: https://github.com/Aider-AI/aider/pull/2641, wish it can be accepted.

**Comment by tninja** [comment]
found that this command can somehow do the simple case for the AI comment: 

/code check added file, find any comment end with AI! and implement the request in place.

Yeah it is definitely not as good as the aider code base implementation. The watch.py do have lots of logic to handle different cases in detail.

**Comment by tninja** [comment]
Seems that recent aider update in 0.71.0: Turn off fancy input and watch files if terminal is dumb.

Not sure if it help on this case?

**Comment by magthe** [comment]
No, it only seems to mean that passing `--watch-files` does exactly nothing. It doesn't break `aider.el, but adding a "AI!" in a comment also has no effect at all.

I still think your suggestion, and PR, to add a command to "run" the comments is the most elegant and appealing solution. Upstream does seem hesitant though.

**Comment by tninja** [comment]
Have a different idea for this feature: Ask aider to implement TODO item in code (eg. TODO in comment), in this commit: https://github.com/tninja/aider.el/commit/b56492f4f131c8b592d0a65604d5a7b2feab9bba

If cursor is inside a function, implement TODOs for that function. Otherwise implement TODOs for the entire current file.

The function is bind to C-c a i key. It use /architect, so the change will be applied after we reviewed that.

**Comment by magthe** [comment]
I have seen TODOs littered throughout projects, checked in, and kept around for what seems forever, so I'm not sure using it as a keyword is a good idea. Making the `AI!` configurable could be a nice idea though.

**Comment by magthe** [comment]
Yes, that's exactly what I mean.

**Comment by tninja** [comment]
This PR can ask aider to implement the requirement in comment under cursor, if there is: https://github.com/tninja/aider.el/pull/61, which is more straight forward: 1. write requirement in comment; 2. trigger the function with C-c a i to implement it in-place.

Also, created issue: https://github.com/tninja/aider.el/issues/62, to track the configurable prompt suggested above.

**Comment by bard** [comment]
> Seems that recent aider update in 0.71.0: Turn off fancy input and watch files if terminal is dumb.
> 
> Not sure if it help on this case?

More background about that (from an Emacs point of view) here: https://github.com/Aider-AI/aider/issues/2716

Running aider in a term/vterm/eat would probably fix this. For now I've gone back to running aider that way even if that means not using aider.el because I found the `ai!` comments the best entry point into the functionality.

**Comment by tninja** [comment]
@bard Thanks for forwarding the issue link here. Great it make progress and let aider detect the dumb term.

Yes confirmed manually running term / vterm works with this. Considering the better integration with other part of emacs, and long term maintainability, still prefer comint solution at this moment.

I'll check and tweak if comint in aider.el can handle th AI! with --watch-files tonight.

**Comment by bard** [comment]
I'm afraid it's a dead end, short of spoofing the TERM variable, which might in turn lead to spurious output, but I'd be happy to be proven wrong.

**Comment by tninja** [comment]
@bard Yes I do tried a little bit and the AI! comment doesn't work on my laptop. Just saw your comment: https://github.com/MatthewZMD/aidermacs/issues/28#issuecomment-2671849092, wondering if the --watch-files work with comint? If it is, maybe I should check how it works in aidermacs.

**Comment by bard** [comment]
> [@bard](https://github.com/bard) Yes I do tried a little bit and the AI! comment doesn't work on my laptop with current aider.el code. Just saw your comment: [MatthewZMD/aidermacs#28 (comment)](https://github.com/MatthewZMD/aidermacs/issues/28#issuecomment-2671849092), wondering if the --watch-files work with comint? If it is, maybe I should check how it works in aidermacs and migrate it here.

If I remember correctly (I also stopped using aidermacs) it does, but with the vterm backend.

**Comment by tninja** [comment]
Close this issue since there is no failure for very long time since aider made the change.. For AI! comment, I am using aider-implement-todo as a work around and now it support AI! given changes in https://github.com/tninja/aider.el/pull/112. Feel free to open separate issue if there is any concern.
